import type { GeneratedComponent, ParsedDesign } from "@/types";
import { tokensToCss, tokensToJson, tokensToTailwindTheme } from "./tokens";

/**
 * Produce a virtual "component library" as a single string the user can copy
 * or save. Real file-system zipping would require a third-party dependency;
 * for ForgeUI's brief, a concatenated multi-file bundle reads cleanly and is
 * easy for the user to split up.
 */

function sectionDivider(filename: string): string {
  return `\n// ${"=".repeat(72)}\n// FILE: ${filename}\n// ${"=".repeat(72)}\n\n`;
}

export function exportLibrary(design: ParsedDesign): string {
  const out: string[] = [];

  out.push(`/**
 * ${design.fileName} — generated by ForgeUI
 * Source: figma.com/file/${design.fileKey}
 * Generated: ${new Date().toISOString()}
 *
 * Drop these files into your project's components/ directory. They use only
 * Tailwind utilities and React — no external runtime dependencies.
 */
`);

  out.push(sectionDivider("design-tokens.css"));
  out.push(tokensToCss(design.tokens));

  out.push(sectionDivider("tailwind.config.ts"));
  out.push(tokensToTailwindTheme(design.tokens));

  out.push(sectionDivider("tokens.json"));
  out.push(tokensToJson(design.tokens));

  for (const c of design.components) {
    out.push(sectionDivider(`components/${c.name}.tsx`));
    out.push(c.source);
  }

  return out.join("\n");
}

export function downloadBlob(filename: string, content: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportComponentFile(c: GeneratedComponent): {
  filename: string;
  content: string;
} {
  return { filename: `${c.name}.tsx`, content: c.source };
}
